### PR TITLE
Configurable qvm-convert-pdf resolution

### PR DESCRIPTION
**Pull request by alimirjamali**
fixes: https://github.com/QubesOS/qubes-issues/issues/2812

The previous default 150ppi resolution was too low.
New default is 300ppi and cofigurable via --resolution option

### CODE REVIEW

**Comment by alimirjamali** [comment]
Making pylint happy(er)

RPC command is stored in a global variable. Adding +resolution at the end of command

**Review by marmarek — CHANGES_REQUESTED** [review]
The resulting PDF needs to have the resolution information included too. Otherwise you'll get a file with unrealistically big pages (my 9cm wide PDF got converted into 50cm wide one).
I see hardcoded resolution in client.py, that wants setting based on the argument.

**Comment by alimirjamali** [comment]
> I see hardcoded resolution in client.py, that wants setting based on the argument.

It is done. I used a shared class level variable for this purpose.

**Review by marmarek — APPROVED** [review]
The class variable is not very nice (better would be an instance attr, passed down through Job object), but since it's a short-lived CLI tool, lets be it

**Pull request merged**
